#!/usr/bin/env python3
"""Exact fixed-shift incoming-source repulsion beyond QR saturation.

For a prime destination k, an exact divisor-square state is (mask, center).
Requiring one additional routed prime q with residue r=q mod k applies the exact
state transition generated by {1,r,r^2}. This classifier compares the complete
ordinary miss closure with the complete augmented miss closure and records
source residues that eliminate every negative-character miss center even when
the augmented seed does not QR-saturate.
"""
from __future__ import annotations

import argparse
import json
import math
from collections import Counter, deque
from functools import lru_cache

from classify_product_character_constraint_closure import closure as product_closure
from classify_branch_aware_character_closure import known_character, legendre_from_residue

HARD_CLASSES = (1, 121, 169, 289, 361, 529)
DESTINATIONS = (7, 11, 19, 23, 31, 47)

EXPECTED_STATE_ONLY = {
    (1, 19, 5): (6, 16),
    (361, 19, 5): (6, 16),
    (1, 31, 2): (5, 9, 14, 25),
    (121, 31, 2): (5, 9, 14, 25),
    (361, 31, 14): (7, 9, 18, 19),
    (1, 47, 6): (7, 9, 14, 17, 18, 21, 25, 27, 28, 34, 37, 42),
    (169, 47, 6): (7, 9, 14, 17, 18, 21, 25, 27, 28, 34, 37, 42),
    (361, 47, 6): (7, 9, 14, 17, 18, 21, 25, 27, 28, 34, 37, 42),
    (529, 47, 6): (7, 9, 14, 17, 18, 21, 25, 27, 28, 34, 37, 42),
}

EXPECTED_NO_EXACT_REPELLER = {
    (169, 19, 1),
    (529, 19, 1),
}

EXPECTED_AGGREGATES = {
    "negative_center_branches": 21,
    "exact_repeller_branches": 19,
    "exact_repeller_residue_pairs": 156,
    "qr_saturating_repeller_residue_pairs": 92,
    "state_only_repeller_branches": 9,
    "state_only_repeller_residue_pairs": 64,
}


@lru_cache(maxsize=None)
def factorization(n: int) -> tuple[tuple[int, int], ...]:
    out: Counter[int] = Counter()
    x = n
    q = 2
    while q * q <= x:
        while x % q == 0:
            out[q] += 1
            x //= q
        q += 1 if q == 2 else 2
    if x > 1:
        out[x] += 1
    return tuple(sorted(out.items()))


class PrimeStateModel:
    def __init__(self, k: int):
        self.k = k
        self.units = tuple(range(1, k))
        self.index = {u: i for i, u in enumerate(self.units)}
        self.type_i = (-pow(4, -1, k)) % k
        self.local = {a: (1, a, a * a % k) for a in self.units}

    def transition(self, state: tuple[int, int], a: int) -> tuple[int, int]:
        mask, center = state
        out = 0
        local = self.local[a]
        remaining = mask
        i = 0
        while remaining:
            if remaining & 1:
                u = self.units[i]
                out |= 1 << self.index[u]
                out |= 1 << self.index[u * local[1] % self.k]
                out |= 1 << self.index[u * local[2] % self.k]
            remaining >>= 1
            i += 1
        return out, center * a % self.k

    def seed_state(self, seed: int) -> tuple[int, int]:
        state = (1 << self.index[1], 1)
        for q, exponent in factorization(seed):
            for _ in range(exponent):
                state = self.transition(state, q % self.k)
        return state

    @lru_cache(maxsize=None)
    def closure(self, start: tuple[int, int]) -> frozenset[tuple[int, int]]:
        seen = {start}
        queue = deque([start])
        while queue:
            state = queue.popleft()
            for a in self.units:
                child = self.transition(state, a)
                if child not in seen:
                    seen.add(child)
                    queue.append(child)
        return frozenset(seen)

    def is_miss(self, state: tuple[int, int]) -> bool:
        mask, center = state
        return (
            ((mask >> self.index[self.type_i]) & 1) == 0
            and ((mask >> self.index[(-center) % self.k]) & 1) == 0
        )

    def p_center(self, state: tuple[int, int]) -> int:
        return 4 * state[1] % self.k

    def mask_residues(self, state: tuple[int, int]) -> frozenset[int]:
        mask, _ = state
        return frozenset(
            u for i, u in enumerate(self.units)
            if (mask >> i) & 1
        )


@lru_cache(maxsize=None)
def model(k: int) -> PrimeStateModel:
    return PrimeStateModel(k)


def class_seed(k: int, h: int) -> int:
    return math.gcd(210, (h + k) // 4)


@lru_cache(maxsize=None)
def local_analysis(k: int, seed: int) -> dict[str, object]:
    m = model(k)
    qrs = frozenset(x * x % k for x in range(1, k))
    base_start = m.seed_state(seed)
    base_closure = m.closure(base_start)
    base_misses = frozenset(state for state in base_closure if m.is_miss(state))
    base_negative = tuple(sorted({
        m.p_center(state)
        for state in base_misses
        if m.p_center(state) not in qrs
    }))

    rows = []
    for r in sorted(qrs):
        augmented_start = m.transition(base_start, r)
        augmented_closure = m.closure(augmented_start)
        augmented_misses = frozenset(
            state for state in augmented_closure if m.is_miss(state)
        )
        if not augmented_misses.issubset(base_misses):
            raise RuntimeError((k, seed, r, "augmented closure escaped ordinary closure"))
        negative = tuple(sorted({
            m.p_center(state)
            for state in augmented_misses
            if m.p_center(state) not in qrs
        }))
        augmented_mask = m.mask_residues(augmented_start)
        rows.append({
            "source_residue": r,
            "augmented_state_count": len(augmented_closure),
            "augmented_miss_count": len(augmented_misses),
            "augmented_center_count": len({m.p_center(state) for state in augmented_misses}),
            "remaining_negative_centers": list(negative),
            "eliminates_all_negative_centers": bool(base_negative) and not negative,
            "qr_saturates": augmented_mask == qrs,
        })

    return {
        "k": k,
        "seed": seed,
        "ordinary_state_count": len(base_closure),
        "ordinary_miss_count": len(base_misses),
        "ordinary_negative_centers": list(base_negative),
        "rows": rows,
    }


def atlas() -> list[dict[str, object]]:
    branches = []
    for k in DESTINATIONS:
        for h in HARD_CLASSES:
            seed = class_seed(k, h)
            if math.gcd(seed, k) != 1:
                continue
            local = local_analysis(k, seed)
            negative = tuple(int(x) for x in local["ordinary_negative_centers"])
            if not negative:
                continue
            exact = tuple(
                int(row["source_residue"])
                for row in local["rows"]
                if row["eliminates_all_negative_centers"]
            )
            saturation = tuple(
                int(row["source_residue"])
                for row in local["rows"]
                if row["eliminates_all_negative_centers"] and row["qr_saturates"]
            )
            state_only = tuple(r for r in exact if r not in saturation)
            branches.append({
                "hard_class": h,
                "destination_k": k,
                "base_seed": seed,
                "ordinary_state_count": local["ordinary_state_count"],
                "ordinary_miss_count": local["ordinary_miss_count"],
                "ordinary_negative_centers": list(negative),
                "exact_repeller_residues": list(exact),
                "qr_saturating_repeller_residues": list(saturation),
                "state_only_repeller_residues": list(state_only),
                "state_only_details": [
                    row for row in local["rows"]
                    if int(row["source_residue"]) in state_only
                ],
            })
    return branches


def assert_atlas(branches: list[dict[str, object]]) -> None:
    negative_count = len(branches)
    exact_branches = sum(bool(row["exact_repeller_residues"]) for row in branches)
    exact_pairs = sum(len(row["exact_repeller_residues"]) for row in branches)
    saturation_pairs = sum(len(row["qr_saturating_repeller_residues"]) for row in branches)
    state_only_rows = {
        (int(row["hard_class"]), int(row["destination_k"]), int(row["base_seed"])):
        tuple(int(r) for r in row["state_only_repeller_residues"])
        for row in branches if row["state_only_repeller_residues"]
    }
    no_exact = {
        (int(row["hard_class"]), int(row["destination_k"]), int(row["base_seed"]))
        for row in branches if not row["exact_repeller_residues"]
    }
    actual = {
        "negative_center_branches": negative_count,
        "exact_repeller_branches": exact_branches,
        "exact_repeller_residue_pairs": exact_pairs,
        "qr_saturating_repeller_residue_pairs": saturation_pairs,
        "state_only_repeller_branches": len(state_only_rows),
        "state_only_repeller_residue_pairs": sum(len(v) for v in state_only_rows.values()),
    }
    if actual != EXPECTED_AGGREGATES:
        raise SystemExit(f"exact-state repulsion aggregates changed: {actual!r}")
    if state_only_rows != EXPECTED_STATE_ONLY:
        raise SystemExit(f"state-only repeller atlas changed: {state_only_rows!r}")
    if no_exact != EXPECTED_NO_EXACT_REPELLER:
        raise SystemExit(f"no-repeller branches changed: {no_exact!r}")


def class_global_intersection(branches: list[dict[str, object]]) -> dict[str, object]:
    # Consume the landed product-aware state set. State keys are
    # (hard_class, fixed residues, individual characters, product constraints).
    _report, state_keys = product_closure(5000)
    by_h = {h: [] for h in HARD_CLASSES}
    for row in branches:
        if row["state_only_repeller_residues"]:
            by_h[int(row["hard_class"])].append(row)

    opportunities = []
    triples = set()
    promotions = set()
    contradictions = set()
    already_positive = set()

    for key in state_keys:
        h, fixed_tuple, characters_tuple, _constraints = key
        fixed = dict(fixed_tuple)
        characters = dict(characters_tuple)
        for branch in by_h.get(int(h), []):
            k = int(branch["destination_k"])
            repellers = set(int(r) for r in branch["state_only_repeller_residues"])
            destination_sign = known_character(k, int(h), fixed, characters)
            for q, sign in characters.items():
                if sign != 1 or q == k or q % k not in repellers:
                    continue
                required = (-k) % q
                if q in fixed:
                    if fixed[q] != required:
                        continue
                elif legendre_from_residue(required, q) != 1:
                    continue
                triple = (int(h), k, int(q))
                triples.add(triple)
                if destination_sign is None:
                    promotions.add(triple)
                    outcome = "new_positive_character_if_destination_misses"
                elif destination_sign == -1:
                    contradictions.add(triple)
                    outcome = "character_contradiction_if_route_and_destination_miss"
                else:
                    already_positive.add(triple)
                    outcome = "destination_character_already_positive"
                opportunities.append({
                    "hard_class": int(h),
                    "destination_k": k,
                    "source_prime": int(q),
                    "source_mod_destination": int(q % k),
                    "required_p_mod_source": int(required),
                    "outcome": outcome,
                })

    return {
        "states_checked": len(state_keys),
        "state_source_destination_opportunities": len(opportunities),
        "distinct_repeller_triples": len(triples),
        "new_positive_character_triples": [
            {"hard_class": h, "destination_k": k, "source_prime": q}
            for h, k, q in sorted(promotions)
        ],
        "character_contradiction_triples": [
            {"hard_class": h, "destination_k": k, "source_prime": q}
            for h, k, q in sorted(contradictions)
        ],
        "already_positive_triples": [
            {"hard_class": h, "destination_k": k, "source_prime": q}
            for h, k, q in sorted(already_positive)
        ],
    }


def analyze() -> dict[str, object]:
    branches = atlas()
    assert_atlas(branches)
    intersection = class_global_intersection(branches)
    return {
        "analysis": "exact-state-incoming-repulsion-v1",
        **EXPECTED_AGGREGATES,
        "destinations_scanned": list(DESTINATIONS),
        "state_only_branches": [
            row for row in branches if row["state_only_repeller_residues"]
        ],
        "no_exact_repeller_branches": [
            row for row in branches if not row["exact_repeller_residues"]
        ],
        "class_global_product_aware_intersection": intersection,
        "claim": (
            "exact fixed-shift state closure exposes incoming positive-source residues that "
            "eliminate every negative miss center without QR-saturating the augmented seed"
        ),
        "claim_boundary": (
            "finite exact-state atlas for prime destinations 7,11,19,23,31,47; route residue "
            "must still be realized on the same branch; positive miss states may remain"
        ),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    report = analyze()
    if args.json:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        print(f"negative-center branches: {report['negative_center_branches']}")
        print(f"exact repeller residue pairs: {report['exact_repeller_residue_pairs']}")
        print(f"state-only repeller residue pairs: {report['state_only_repeller_residue_pairs']}")
        print(report["class_global_product_aware_intersection"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
